#!/bin/bash

# -- User -- #
# TODO: This group might not exist yet, will it be created (?)
# sudo usermod -aG docker ${USER}
#
# TODO: Should this script be idemopotent? I would need to add
# a lot more checks for existing files, etc. Would be nice for
# when I'm updating / fixing this script.

# -- GNOME Desktop settings -- #

# Remap caps to escape, both shift to caps
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape','shift:both_capslock']"

# Disable tap-to-click on touchpad
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click false
# Set scroll direction like a sane person
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false

# Configure screen blanking to 30 minute timeout (not available in GUI)
gsettings set org.gnome.desktop.session idle-delay 1800
gsettings set org.gnome.desktop.screensaver lock-delay 0
gsettings set org.gnome.desktop.screensaver lock-enabled true

# -- Repositories -- #

# Dependencies to support HTTPS repos (e.g. ST3, Docker, Slack)
sudo apt-get -y --install-recommends install apt-transport-https ca-certificates \
	curl gnupg software-properties-common

# New key management strategy, 'apt-key add' is deprecated
sudo install -m 0755 -d /etc/apt/keyrings

# Collect system information
ARCH=$(dpkg --print-architecture)
CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")

# Add Sublime repo (dev)
curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/sublimehq.gpg
sudo chmod a+r /etc/apt/keyrings/sublimehq.gpg
echo \
  "deb [arch=$ARCH signed-by=/etc/apt/keyrings/sublimehq.gpg] https://download.sublimetext.com/ apt/dev/" | \
  sudo tee /etc/apt/sources.list.d/sublime-text.list > /dev/null

# Add Spotify repo
# NOTE: Disabling as of 2023-12-06; mostly using work laptop right now, may
# revisit if I start using my personal Linux laptop more
# curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
# echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

# Add Docker repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $CODENAME stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Add InSync repo
# NOTE: Ibid. note for Spotify
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
# echo "deb http://apt.insync.io/ubuntu bionic non-free contrib" | sudo tee /etc/apt/sources.list.d/insync.list

# Perform an update with all of the new repos
sudo apt-get update

# Install all my applications
# TODO: Split these into "gui" and "no-gui"
# NOTE: As of 2023-12-06, removing: chromium-browser, insync, npm, spotify-client, transmission, vlc, zutils; adding: docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin, tmux
# NOTE: As of 2023-12-13, renaming 'slack-desktop' to 'slack'
sudo apt-get install -y --install-recommends \
	cmake \
	docker-ce \
	docker-ce-cli \
	containerd.io \
	docker-buildx-plugin \
	docker-compose-plugin \
	filezilla \
	git \
	ncdu \
	ninja-build \
	picocom \
	python3-pip \
	slack \
	stow \
	sublime-text \
	sublime-merge \
	tmux \
	vim \
	xclip

# TODO:
# 
# Things that live in my "apps" folder
# - Add obsidian, would also be neat to get "desktop" support (e.g. icon,
#   searchable with super key) working
# - Add Saleae Logic

# Others not on list yet:
# bison
# flex
# inkscape
# npm
# openocd
# 
# Specific to st-utils
# libusb-1.0
# libusb-1.0-0-dev

# -- Python -- #
# pip3 install --user \
# 	meson \
# 	pipenv
