#!/bin/bash

# -- GNOME Desktop settings -- #

# Remap caps to escape, both shift to caps
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape','shift:both_capslock']"

# Disable tap-to-click on touchpad
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click false

# -- Repositories -- #

# Add Sublime repo (dev)
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/dev/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

# Add Spotify repo
curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

# Add Docker repo
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

# Add InSync repo
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
echo "deb http://apt.insync.io/ubuntu bionic non-free contrib" | sudo tee /etc/apt/sources.list.d/insync.list

# Make sure apt-transport-https, ca-certificates, and software-properties-common
# are installed *before* trying to update with HTTPS repos (e.g. ST3, Docker,
# Slack)
sudo apt -y --install-recommends install apt-transport-https ca-certificates \
	software-properties-common

# Perform an update with all of the new repos
sudo apt update

# Install all my applications
sudo apt install -y --install-recommends \
	chromium-browser \
	cmake \
	docker-ce \
	filezilla \
	git \
	insync \
	meson \
	ncdu \
	ninja-build \
	npm \
	python3-pip \
	slack-desktop \
	spotify-client \
	sublime-text \
	sublime-merge \
	vim \
	vlc \
	xclip
